# Generated by Django 2.0.4 on 2018-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180422_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puser',
            name='user_rec',
            field=models.CharField(max_length=200),
        ),
    ]
